const express = require('express')
const app = express()
const port = process.argv[2] || 8000

const ANALYTICS = require('../index.js')

const oneDay = 1000 * 60 * 60 * 24
ANALYTICS.setup(app, {
  path: `${__dirname}/analytics`, // path to store data
  debug: true, // print debug logs to console
  idttl: oneDay, // (1 day) how long before anonimyzing user id
  admin: { // enable admin API/dashboard (could also be set to: true)
    // path to custom dashboard.html && login.html files
    // dashboard: `${__dirname}/www/custom-analytics-gui`,
    // custom URL to access admin dashboard: http://[host]/analytics
    // route: 'analytics',
    // custom secret used to create the session cookie/token
    // secret: 'o9gdlXwoFY5NPTzzeeuFXeF/ATUQvLHW8tquxv3pfE6nZaFsKdWvK',
    // custom admin password hash, generated by: npm run hashpw [PW]
    hash: '$2a$10$Fs.gnowR98rmzKqqCkzNGePF2n5PCD0ZKHNYfzNsTjTcrBTVW4Aeu',
    // name of session cookie (json-web-token)
    token: 'CmdAuth'
  }
})

app.use(express.static(`${__dirname}/www`))

const server = app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}, CTRL + C to shutdown`)
})

ANALYTICS.live(server)
/*
  // alternatively, if sockets.io is already in use...

  const io = require('socket.io')(server)
  io.on('connection', (socket) => {
    console.log('a new client connected!', socket.id)
  })

  ANALYTICS.live(server, io)
*/
